// ES256 signing for settlement records.
//
// The exchange's signing key lives in env (COCORE_EXCHANGE_PRIVATE_KEY_JWK)
// and the matching public-key fingerprint is published in the
// dev.cocore.compute.exchangeAttestation record so verifiers can
// resolve the key by walking the receipt → attestation chain. The
// public key also goes in the did:web doc's verificationMethod for
// alternate-resolution paths.
//
// We sign over the canonical-JSON encoding of every settlement field
// EXCEPT `sig` itself. Same canonical encoding the provider uses for
// receipts (sorted keys, no whitespace, integer-only). That way a
// receipt-style verifier just needs the signing key to validate.

import { webcrypto } from "node:crypto";

import { canonicalBytes } from "@cocore/sdk/canonical";
import type { SettlementRecord } from "@cocore/sdk/types";

const { subtle } = webcrypto;

/** ES256 (P-256) JWK shape. Public-half fields (x, y, crv, kty) plus
 *  the secret scalar (d). Generated by scripts/generate-atproto-jwk.sh
 *  or any compatible tool. */
export interface PrivateJwk {
  kty: "EC";
  crv: "P-256";
  x: string;
  y: string;
  d: string;
  alg?: "ES256";
  kid?: string;
}

interface PublicJwk {
  kty: "EC";
  crv: "P-256";
  x: string;
  y: string;
  alg?: "ES256";
  kid?: string;
}

function publicHalf(priv: PrivateJwk): PublicJwk {
  return {
    kty: priv.kty,
    crv: priv.crv,
    x: priv.x,
    y: priv.y,
    ...(priv.alg ? { alg: priv.alg } : {}),
    ...(priv.kid ? { kid: priv.kid } : {}),
  };
}

function base64urlEncode(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

async function sha256(bytes: Uint8Array): Promise<Uint8Array> {
  return new Uint8Array(await subtle.digest("SHA-256", bytes));
}

/** ES256 signature (raw R||S, 64 bytes) over the canonical bytes of
 *  the record minus its `sig` field. Returns base64url with no
 *  padding — same shape we use for receipts. Generic because dispute
 *  records (dev.cocore.compute.dispute) reuse the same signing path
 *  as settlements. */
export async function signRecord(
  record: Record<string, unknown> & { sig?: string },
  priv: PrivateJwk,
): Promise<string> {
  // Strip any pre-existing sig before canonicalizing.
  const { sig: _drop, ...rest } = record;
  void _drop;
  const bytes = canonicalBytes(rest);
  const key = await subtle.importKey("jwk", priv, { name: "ECDSA", namedCurve: "P-256" }, false, [
    "sign",
  ]);
  const sigBuf = await subtle.sign({ name: "ECDSA", hash: { name: "SHA-256" } }, key, bytes);
  return base64urlEncode(sigBuf);
}

/** Settlement-typed wrapper around {@link signRecord}, kept for
 *  backwards compatibility with callers that pass a SettlementRecord
 *  literal. */
export function signSettlement(record: SettlementRecord, priv: PrivateJwk): Promise<string> {
  return signRecord(record as unknown as Record<string, unknown>, priv);
}

/** SHA-256 fingerprint of the public-key JWK's canonical form. Goes
 *  into the exchangeAttestation record so verifiers can compare with
 *  the key they fetch out-of-band from the did doc. */
export async function publicKeyFingerprint(priv: PrivateJwk): Promise<string> {
  const pub = publicHalf(priv);
  const bytes = canonicalBytes(pub);
  const digest = await sha256(bytes);
  return base64urlEncode(digest);
}

/** Convenience: parse the env JWK string into a typed PrivateJwk.
 *  Throws if the shape is wrong. */
export function parsePrivateJwk(json: string): PrivateJwk {
  const v = JSON.parse(json) as Record<string, unknown>;
  if (
    v.kty !== "EC" ||
    v.crv !== "P-256" ||
    typeof v.x !== "string" ||
    typeof v.y !== "string" ||
    typeof v.d !== "string"
  ) {
    throw new Error("expected EC P-256 private JWK with x/y/d strings");
  }
  return v as unknown as PrivateJwk;
}
